/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
/**
 * base64DecodeBatch(items: string[]): Promise<Buffer[]> — accepts padded or
 * unpadded standard-alphabet input, but strictly canonical: wrong padding,
 * whitespace, or non-alphabet characters reject the batch with
 * "item {i}: base64Decode: {cause}"
 */
export declare function base64DecodeBatch(items: Array<string>): Promise<Buffer[]>

/**
 * base64EncodeBatch(items: Array<Buffer | string>): Promise<string[]> —
 * standard alphabet, padded (matches Buffer.toString('base64')); strings are
 * encoded from their UTF-8 bytes
 */
export declare function base64EncodeBatch(items: Array<Buffer | string>): Promise<string[]>

/** blake3HexBatch(items: Buffer[]): Promise<string[]> — lowercase hex, 64 chars per item */
export declare function blake3HexBatch(items: Array<Buffer>): Promise<string[]>

/**
 * brotliCompressBatch(items: Buffer[], opts?: { quality?: number, lgwin?: number }): Promise<Buffer[]>
 * — quality 0-11 (default 5), lgwin 10-24 (default 22)
 */
export declare function brotliCompressBatch(items: Array<Buffer>, opts?: BrotliOptions | undefined | null): Promise<Buffer[]>

/**
 * brotliDecompressBatch(items: Buffer[]): Promise<Buffer[]> — corrupt input
 * rejects the batch with "item {i}: brotliDecompress: {cause}"
 */
export declare function brotliDecompressBatch(items: Array<Buffer>): Promise<Buffer[]>

/**
 * Options for brotliCompressBatch. quality 0-11 (default 5); lgwin — log2 of
 * the sliding window — 10-24 (default 22).
 */
export interface BrotliOptions {
  quality?: number
  lgwin?: number
}

/**
 * byteLenBatch(items: Array<Buffer | string>): Promise<number[]>
 *
 * UTF-8 byte length per item (a Buffer's byte length as-is; strings measured
 * after UTF-16 -> UTF-8 conversion).
 */
export declare function byteLenBatch(items: Array<Buffer | string>): Promise<number[]>

/**
 * chunkByTokensBatch(items: string[], cfg: ChunkByTokensConfig): Promise<string[]>
 *
 * Per item: a JSON array string of chunk strings — windows of `maxTokens`
 * BPE tokens advancing by `maxTokens - overlap`, sliced from the original
 * string with window edges snapped down to character boundaries (so with
 * overlap 0 the chunks concatenate back to the exact input). An empty item
 * yields "[]". Invalid config throws synchronously with status InvalidArg;
 * per-item failures reject the batch as "item {i}: chunkByTokens: {cause}".
 */
export declare function chunkByTokensBatch(items: Array<string>, cfg: ChunkByTokensConfig): Promise<string[]>

/**
 * Config for chunkByTokensBatch. Windows of `maxTokens` tokens advance by
 * `maxTokens - overlap` tokens; `overlap` defaults to 0 and must be < maxTokens.
 */
export interface ChunkByTokensConfig {
  encoding: 'cl100k_base' | 'o200k_base'
  maxTokens: number
  overlap?: number
}

/**
 * compilePipelinePlan(planJson: string, inputKind: 'bytes' | 'str' | 'either'): ExternalObject
 * Compile a plan ONCE (JSON parse + regex compilation + chain type-check) and
 * reuse the returned handle across any number of runPipeline* calls.
 */
export declare function compilePipelinePlan(planJson: string, inputKind: 'bytes' | 'str' | 'either'): ExternalObject<'PipelinePlan'>

/** Configure the global rayon pool size (1-1024). Call once, before first use. */
export declare function configureThreads(n: number): void

/**
 * countTokensBatch(items: string[], encoding: 'cl100k_base' | 'o200k_base'): Promise<number[]>
 *
 * BPE token count per item. Uses ordinary encoding: special-token text like
 * "<|endoftext|>" counts as plain text. Unknown encodings throw synchronously
 * with status InvalidArg. Each rayon thread pays a one-time vocab build at
 * its first use of an encoding — the event loop never blocks.
 */
export declare function countTokensBatch(items: Array<string>, encoding: 'cl100k_base' | 'o200k_base'): Promise<number[]>

/**
 * crc32cHexBatch(items: Array<Buffer | string>): Promise<string[]> —
 * CRC-32C (Castagnoli, iSCSI/ext4 polynomial), 8 lowercase hex chars per item
 */
export declare function crc32cHexBatch(items: Array<Buffer | string>): Promise<string[]>

/**
 * crc32HexBatch(items: Array<Buffer | string>): Promise<string[]> —
 * CRC-32/IEEE (zlib/gzip/PNG polynomial), 8 lowercase hex chars per item
 */
export declare function crc32HexBatch(items: Array<Buffer | string>): Promise<string[]>

/**
 * csvToNdjsonBatch(items: Array<Buffer | string>, opts?: CsvToNdjsonOptions): Promise<string[]>
 *
 * One item = one whole CSV file/chunk; each resolves to NDJSON (one JSON
 * object per row, '
'-joined, all values as JSON strings). Keys come from
 * the header row when hasHeader (default), else col0..colN. Invalid options
 * throw synchronously with status InvalidArg; a malformed row, invalid UTF-8,
 * or unknown select column rejects the batch as "item {i}: csvToNdjson: {cause}".
 */
export declare function csvToNdjsonBatch(items: Array<Buffer | string>, opts?: CsvToNdjsonOptions | undefined | null): Promise<string[]>

/**
 * Options for csvToNdjsonBatch. `delimiter` (default ",") and `quote`
 * (default "\"") must be single ASCII characters. `hasHeader` defaults to
 * true. `select` projects the named columns in the given order.
 */
export interface CsvToNdjsonOptions {
  delimiter?: string
  hasHeader?: boolean
  quote?: string
  select?: Array<string>
}

/**
 * diffBatch(a: string[], b: string[], opts?: { context?: number }): Promise<string[]>
 *
 * Unified-diff text per pair: hunks only (`@@ -l,n +l,n @@` headers, no
 * `---`/`+++` file header). Equal inputs yield an empty string. Inputs not
 * ending in a newline get the standard `\ No newline at end of file` marker.
 * `context` is the unchanged-line radius around each hunk (0-100, default 3).
 */
export declare function diffBatch(a: Array<string>, b: Array<string>, opts?: DiffOptions | undefined | null): Promise<string[]>

export interface DiffOptions {
  /** Unchanged-line radius around each hunk (0-100, default 3). */
  context?: number
}

/**
 * expandGlob(patterns: string[]): Promise<string[]>
 * Expands glob patterns to the FILE paths matching them; the filesystem walk
 * runs on a rayon thread — off libuv. The GlobSet is built ONCE up front on
 * the JS thread, so an invalid pattern throws synchronously as InvalidArg,
 * naming the pattern. `*` does not cross `/` (use `**` to recurse). Patterns
 * without metacharacters pass through as literal paths without touching the
 * filesystem. Resolves the union of all matches, sorted and deduplicated.
 */
export declare function expandGlob(patterns: Array<string>): Promise<string[]>

/** gunzipBatch(items: Buffer[]): Promise<Buffer[]> */
export declare function gunzipBatch(items: Array<Buffer>): Promise<Buffer[]>

/** gzipBatch(items: Buffer[], level?: number): Promise<Buffer[]> — level 0-9, default 6 */
export declare function gzipBatch(items: Array<Buffer>, level?: number | undefined | null): Promise<Buffer[]>

/**
 * hexDecodeBatch(items: string[]): Promise<Buffer[]> — accepts upper, lower,
 * or mixed case; odd length or non-hex characters reject the batch with
 * "item {i}: hexDecode: {cause}"
 */
export declare function hexDecodeBatch(items: Array<string>): Promise<Buffer[]>

/**
 * hexEncodeBatch(items: Array<Buffer | string>): Promise<string[]> — lowercase
 * (matches Buffer.toString('hex')); strings are encoded from their UTF-8 bytes
 */
export declare function hexEncodeBatch(items: Array<Buffer | string>): Promise<string[]>

/** The `{attr: string}` form of HtmlExtractConfig.extract. */
export interface HtmlExtractAttr {
  attr: string
}

/**
 * htmlExtractBatch(items: Array<Buffer | string>, cfg: HtmlExtractConfig): Promise<string[]>
 *
 * CSS-selector extraction (scraper). The selector is parsed ONCE on the JS
 * thread — invalid selectors throw synchronously with status InvalidArg.
 * all=false (default): the first match's text/outer-HTML/attr, '' if there
 * is no match (or the match lacks the attr). all=true: a JSON array string
 * with one entry per match (missing attr -> null). Buffer items must be
 * UTF-8; a non-UTF-8 item rejects the batch as "item {i}: htmlExtract: ...".
 */
export declare function htmlExtractBatch(items: Array<Buffer | string>, cfg: HtmlExtractConfig): Promise<string[]>

/**
 * Config for htmlExtractBatch. `selector` is parsed once on the JS thread
 * (invalid selectors throw synchronously with status InvalidArg).
 */
export interface HtmlExtractConfig {
  selector: string
extract: 'text' | 'html' | { attr: string }
all?: boolean
}

/**
 * htmlToTextBatch(items: string[], opts?: HtmlToTextOptions): Promise<string[]>
 *
 * html2text plain-text rendering wrapped at `width` columns (default 80,
 * 1-1000; out-of-range throws synchronously with status InvalidArg).
 */
export declare function htmlToTextBatch(items: Array<string>, opts?: HtmlToTextOptions | undefined | null): Promise<string[]>

/** Options for htmlToTextBatch. `width` = output wrap column, 1-1000, default 80. */
export interface HtmlToTextOptions {
  width?: number
}

/**
 * jsonPluckBatch(items: Array<Buffer | string>, path: string): Promise<Array<string | null>>
 *
 * Lazy gjson path extraction; `null` when the path does not exist. Strings
 * yield their raw content; objects/arrays/booleans/numbers and JSON null
 * yield their JSON text (a JSON null value is the string "null", NOT JS null).
 */
export declare function jsonPluckBatch(items: Array<Buffer | string>, path: string): Promise<Array<string | null>>

/**
 * jsonValidateBatch(items: Array<Buffer | string>): Promise<boolean[]>
 *
 * Iterative RFC 8259 syntax check — no value tree is built and no recursion
 * happens, so nesting depth is unlimited (deep documents validate true,
 * matching JSON.parse). String content must be valid UTF-8; `\uXXXX` escapes
 * need 4 hex digits (lone surrogates are accepted, as JSON.parse does).
 */
export declare function jsonValidateBatch(items: Array<Buffer | string>): Promise<boolean[]>

/** levenshteinBatch(a: string[], b: string[]): Promise<number[]> */
export declare function levenshteinBatch(a: Array<string>, b: Array<string>): Promise<number[]>

/** levenshteinEach(a: string[], b: string[]): Promise<number>[] */
export declare function levenshteinEach(a: Array<string>, b: Array<string>): Promise<number>[]

/** lowercaseBatch(items: string[]): Promise<string[]> — Unicode-aware full lowercasing */
export declare function lowercaseBatch(items: Array<string>): Promise<string[]>

/**
 * Options for markdownToHtmlBatch. `gfm` defaults true; `unsafe` defaults
 * false (raw HTML in the markdown is escaped — enable it only together with
 * sanitizeHtmlBatch on the output).
 */
export interface MarkdownHtmlOptions {
  gfm?: boolean
  tables?: boolean
  footnotes?: boolean
  smartPunct?: boolean
  unsafe?: boolean
}

/**
 * markdownToHtmlBatch(items: string[], opts?: MarkdownHtmlOptions): Promise<string[]>
 *
 * comrak (CommonMark). gfm=true by default (strikethrough, tagfilter,
 * tables, autolink, tasklist); unsafe=false by default, so raw HTML in the
 * markdown is escaped — pair unsafe:true with sanitizeHtmlBatch.
 */
export declare function markdownToHtmlBatch(items: Array<string>, opts?: MarkdownHtmlOptions | undefined | null): Promise<string[]>

/**
 * multiFindBatch(items: string[], cfg: MultiFindConfig): Promise<string[]>
 *
 * Per item: a JSON array string of {p: patternIndex, s: startByte, e: endByte},
 * leftmost-longest, non-overlapping, optionally capped at `limit` matches.
 * The automaton is built once on the JS thread (invalid config throws
 * synchronously with status InvalidArg).
 */
export declare function multiFindBatch(items: Array<string>, cfg: MultiFindConfig): Promise<string[]>

/**
 * Config for multiFindBatch. `limit` (>= 1) caps matches per item.
 * `caseInsensitive` folds ASCII letters only.
 */
export interface MultiFindConfig {
  patterns: Array<string>
  caseInsensitive?: boolean
  limit?: number
}

/**
 * multiReplaceBatch(items: string[], cfg: MultiReplaceConfig): Promise<string[]>
 *
 * Aho-Corasick replace-all with leftmost-longest match semantics; the
 * automaton is built once on the JS thread (invalid config throws
 * synchronously with status InvalidArg).
 */
export declare function multiReplaceBatch(items: Array<string>, cfg: MultiReplaceConfig): Promise<string[]>

/**
 * Config for multiReplaceBatch. `replacements` as an array must match
 * `patterns` in length; as a single string it applies to every pattern.
 * `caseInsensitive` folds ASCII letters only.
 */
export interface MultiReplaceConfig {
  patterns: Array<string>
  replacements: Array<string> | string
  caseInsensitive?: boolean
}

/**
 * One NDJSON filter: gjson `path`, comparison `op`, and the value to compare
 * against (required for eq/ne/gt/lt, ignored for exists).
 */
export interface NdjsonFilter {
  path: string
  op: 'eq' | 'ne' | 'gt' | 'lt' | 'exists'
  value?: string | number
}

/**
 * ndjsonTransformBatch(items: Array<Buffer | string>, cfg: NdjsonTransformConfig): Promise<string[]>
 *
 * One item = one NDJSON chunk. Per line: blank lines are skipped; all
 * `filter` predicates must pass (eq/ne compare gjson text, gt/lt compare
 * numerically, exists checks presence); `project` rebuilds the line as
 * {last path segment or full path: value, missing -> null}, otherwise the
 * line passes through verbatim. Survivors are '
'-joined per item. Invalid
 * config throws synchronously with status InvalidArg; an invalid JSON line
 * rejects the batch as "item {i}: ndjsonTransform: line {n}: invalid JSON".
 */
export declare function ndjsonTransformBatch(items: Array<Buffer | string>, cfg: NdjsonTransformConfig): Promise<string[]>

/**
 * Config for ndjsonTransformBatch: `filter` keeps only lines where ALL
 * predicates pass; `project` rebuilds each surviving line from gjson paths.
 * At least one of the two must be set.
 */
export interface NdjsonTransformConfig {
  filter?: Array<NdjsonFilter>
  project?: Array<string>
}

/** normalizeBatch(items: string[], form: 'NFC'|'NFD'|'NFKC'|'NFKD'): Promise<string[]> */
export declare function normalizeBatch(items: Array<string>, form: 'NFC' | 'NFD' | 'NFKC' | 'NFKD'): Promise<string[]>

/**
 * regexCountBatch(items: string[], pattern: string): Promise<number[]>
 *
 * Count of non-overlapping matches per item. Rust `regex` syntax; compiled
 * once, invalid patterns throw synchronously with status InvalidArg.
 */
export declare function regexCountBatch(items: Array<string>, pattern: string): Promise<number[]>

/**
 * regexExtractBatch(items: string[], pattern: string, group?: number): Promise<Array<string | null>>
 *
 * First match per item, optionally a capture group (default 0 = whole match).
 * NO MATCH -> `null` — the kernel convention (like jsonPluckBatch's
 * missing-path null). This deliberately diverges from the regexExtract STAGE,
 * which treats no-match as a per-item error. The pattern is compiled once for
 * the whole batch; `group` is validated against its capture count.
 */
export declare function regexExtractBatch(items: Array<string>, pattern: string, group?: number | undefined | null): Promise<Array<string | null>>

/**
 * regexReplaceBatch(items: string[], pattern: string, replacement: string): Promise<string[]>
 *
 * `replace_all` with Rust regex replacement syntax (`$1`, `${name}`; `$&` is
 * literal) — identical to the regexReplace pipeline stage. The pattern is
 * compiled once for the whole batch.
 */
export declare function regexReplaceBatch(items: Array<string>, pattern: string, replacement: string): Promise<string[]>

/**
 * regexTestBatch(items: string[], pattern: string): Promise<boolean[]>
 *
 * Rust `regex` syntax (no lookaround/backreferences); compiled once, invalid
 * patterns throw synchronously with status InvalidArg.
 */
export declare function regexTestBatch(items: Array<string>, pattern: string): Promise<boolean[]>

/**
 * runPipelineCollect(plan: string | ExternalObject, items: Array<Buffer> | Array<string>): Promise<string[] | Buffer[]>
 * failFast: rejects with "item {i}: {op}: {cause}" on the first failing item.
 */
export declare function runPipelineCollect(plan: string | ExternalObject<'PipelinePlan'>, items: Array<Buffer> | Array<string>): Promise<string[] | Buffer[]>

/**
 * runPipelineCount(plan: string | ExternalObject, items: Array<Buffer> | Array<string>): Promise<number>
 * failFast mode: an item error still rejects; settled mode: count of successful items.
 */
export declare function runPipelineCount(plan: string | ExternalObject<'PipelinePlan'>, items: Array<Buffer> | Array<string>): Promise<number>

/**
 * runPipelineFiles(plan: string | ExternalObject, paths: string[]): Promise<string[] | Buffer[]>
 * Source variant: reads each file on a rayon thread (bytes input), then runs the chain.
 * failFast: a read or stage error rejects as "item {i}: ...".
 */
export declare function runPipelineFiles(plan: string | ExternalObject<'PipelinePlan'>, paths: Array<string>): Promise<string[] | Buffer[]>

/**
 * runPipelineFilesCount(plan: string | ExternalObject, paths: string[]): Promise<number>
 * Count source variant: reads and runs every file on rayon threads; only the
 * count crosses the boundary. failFast mode: any read or stage error rejects
 * as "item {i}: ..."; settled mode: count of successful items.
 */
export declare function runPipelineFilesCount(plan: string | ExternalObject<'PipelinePlan'>, paths: Array<string>): Promise<number>

/**
 * runPipelineFilesSettled(plan: string | ExternalObject, paths: string[]): Promise<SettledItem[]>
 * Settled source variant: read/stage errors land in per-item {ok: false, error}.
 */
export declare function runPipelineFilesSettled(plan: string | ExternalObject<'PipelinePlan'>, paths: Array<string>): Promise<Array<SettledItem>>

/**
 * runPipelineFilesStream(plan: string | ExternalObject, paths: string[], onItem: (err, item) => void): void
 * Stream source variant: each file is read on a rayon thread, then run through
 * the chain. Exactly one callback per path, fired in COMPLETION order; read
 * failures arrive as {ok: false, error: "item {i}: readFile '{path}': ..."}.
 */
export declare function runPipelineFilesStream(plan: string | ExternalObject<'PipelinePlan'>, paths: Array<string>, onItem: (err: Error | null, item: StreamItem) => void): void

/**
 * runPipelineFilesWriteFiles(plan: string | ExternalObject, paths: string[]): Promise<string[]>
 * WriteFiles source variant: plan terminal must be {kind: "writeFiles", dir, ext?}.
 * Reads AND writes happen on rayon threads; input file i lands at `{dir}/{i}{ext}`.
 * Read failures are item errors: "item {i}: readFile '{path}': {cause}".
 */
export declare function runPipelineFilesWriteFiles(plan: string | ExternalObject<'PipelinePlan'>, paths: Array<string>): Promise<string[]>

/**
 * runPipelineSettled(plan: string | ExternalObject, items: Array<Buffer> | Array<string>): Promise<SettledItem[]>
 * Never rejects on item errors: each element is {ok, value?, error?}.
 */
export declare function runPipelineSettled(plan: string | ExternalObject<'PipelinePlan'>, items: Array<Buffer> | Array<string>): Promise<Array<SettledItem>>

/**
 * runPipelineStream(plan: string | ExternalObject, items: Array<Buffer> | Array<string>, onItem: (err, item) => void): void
 * Exactly one callback per item, fired in COMPLETION order; no call after the
 * last one. The JS layer wraps this into an async iterator.
 */
export declare function runPipelineStream(plan: string | ExternalObject<'PipelinePlan'>, items: Array<Buffer> | Array<string>, onItem: (err: Error | null, item: StreamItem) => void): void

/**
 * runPipelineWriteFiles(plan: string | ExternalObject, items: Array<Buffer> | Array<string>): Promise<string[]>
 * Plan terminal must be {kind: "writeFiles", dir, ext?}. Writes item i to `{dir}/{i}{ext}`
 * on rayon threads and resolves with the written paths.
 */
export declare function runPipelineWriteFiles(plan: string | ExternalObject<'PipelinePlan'>, items: Array<Buffer> | Array<string>): Promise<string[]>

/**
 * sanitizeHtmlBatch(items: string[], policy?: SanitizeHtmlPolicy): Promise<string[]>
 *
 * ammonia sanitization. No policy = ammonia defaults (scripts/styles and
 * event handlers stripped, conservative tag/attribute/scheme whitelists,
 * comments stripped, links get rel="noopener noreferrer"). Invalid policies
 * throw synchronously with status InvalidArg.
 */
export declare function sanitizeHtmlBatch(items: Array<string>, policy?: SanitizeHtmlPolicy | undefined | null): Promise<string[]>

/**
 * Sanitization policy for sanitizeHtmlBatch. Every provided field REPLACES
 * the corresponding ammonia default; omitted fields keep ammonia defaults.
 * `allowedAttrs` maps tag name -> allowed attributes and is the WHOLE
 * attribute policy when present ("*" = any tag; without a "*" key even
 * ammonia's default generic attributes lang/title are dropped).
 */
export interface SanitizeHtmlPolicy {
  allowedTags?: Array<string>
  allowedAttrs?: Record<string, Array<string>>
  urlSchemes?: Array<string>
  stripComments?: boolean
}

export interface SettledItem {
  ok: boolean
  value?: string | Buffer
  error?: string
}

/** sha256HexBatch(items: Buffer[]): Promise<string[]> — lowercase hex, 64 chars per item */
export declare function sha256HexBatch(items: Array<Buffer>): Promise<string[]>

/**
 * similarityBatch(a: string[], b: string[], metric: 'jaro' | 'jaroWinkler' | 'sorensenDice' | 'normalizedLevenshtein' | 'normalizedDamerau'): Promise<number[]>
 *
 * Per-pair similarity score in [0, 1] (1 = identical). All metrics operate on
 * Unicode scalar values (chars), not bytes.
 */
export declare function similarityBatch(a: Array<string>, b: Array<string>, metric: 'jaro' | 'jaroWinkler' | 'sorensenDice' | 'normalizedLevenshtein' | 'normalizedDamerau'): Promise<number[]>

/**
 * sortNumbers(items: Float64Array): Promise<Float64Array>
 *
 * Parallel sort within the one array. total_cmp order:
 * -NaN < -Infinity < ... < -0 < +0 < ... < +Infinity < +NaN.
 */
export declare function sortNumbers(items: Float64Array): Promise<Float64Array>

/**
 * sortStrings(items: string[]): Promise<string[]>
 *
 * Lexicographic by Unicode scalar value (Rust `Ord` on str), not locale collation.
 */
export declare function sortStrings(items: Array<string>): Promise<string[]>

export interface StreamItem {
  index: number
  ok: boolean
  value?: string | Buffer
  error?: string
}

/** How many threads rayon will fan work across (side-effect-free). */
export declare function threadCount(): number

/** trimBatch(items: string[]): Promise<string[]> — trims Unicode whitespace from both ends */
export declare function trimBatch(items: Array<string>): Promise<string[]>

/**
 * truncateTokensBatch(items: string[], cfg: TruncateTokensConfig): Promise<string[]>
 *
 * Per item: the decode of the first (keep 'start', default) or last ('end')
 * `maxTokens` BPE tokens. Items already within budget pass through
 * byte-identical. A cut inside a multi-byte character drops the fragment, so
 * results are always valid prefixes ('start') / suffixes ('end') of the
 * input. Invalid config throws synchronously with status InvalidArg;
 * per-item failures reject the batch as "item {i}: truncateTokens: {cause}".
 */
export declare function truncateTokensBatch(items: Array<string>, cfg: TruncateTokensConfig): Promise<string[]>

/**
 * Config for truncateTokensBatch. `keep: 'start'` (default) keeps the first
 * `maxTokens` tokens, `'end'` the last.
 */
export interface TruncateTokensConfig {
  encoding: 'cl100k_base' | 'o200k_base'
  maxTokens: number
  keep?: 'start' | 'end'
}

/** uppercaseBatch(items: string[]): Promise<string[]> — Unicode-aware full uppercasing */
export declare function uppercaseBatch(items: Array<string>): Promise<string[]>

/** xxh3HexBatch(items: Buffer[]): Promise<string[]> — xxh3_64, lowercase hex, 16 chars per item */
export declare function xxh3HexBatch(items: Array<Buffer>): Promise<string[]>

/** xxh64HexBatch(items: Buffer[]): Promise<string[]> — xxh64 seed 0, lowercase hex, 16 chars per item */
export declare function xxh64HexBatch(items: Array<Buffer>): Promise<string[]>

/** zstdCompressBatch(items: Buffer[], level?: number): Promise<Buffer[]> — level 1-22, default 3 */
export declare function zstdCompressBatch(items: Array<Buffer>, level?: number | undefined | null): Promise<Buffer[]>

/** zstdDecompressBatch(items: Buffer[]): Promise<Buffer[]> */
export declare function zstdDecompressBatch(items: Array<Buffer>): Promise<Buffer[]>
